### ISSUE TITLE
Position tokens for game frames also include dead players.

### ISSUE THREAD

**Issue by JanEricNitschke** [pnxenopoulos/awpy#142]
Position tokens for game frames also include dead players.

Loops over players do not check if the player is alive before adding him to the position token.

https://github.com/pnxenopoulos/csgo/blob/main/csgo/analytics/nav.py#L189
https://github.com/pnxenopoulos/csgo/blob/main/csgo/analytics/nav.py#L197

**Comment by pnxenopoulos** [comment]
Fixed in #141
