### ISSUE TITLE
Wrong dtype for SteamID columns in kills dataframe

### ISSUE THREAD

**Issue by belgarathcjd** [pnxenopoulos/awpy#148]
**Describe the bug**
In any of the SteamID columns, if one of the steamIDs is None, the dtype for that column is set as float64. When this happens the last two digits of all SteamIDs are lost because of rounding. I imagine this also happens in other dataframes with SteamID columns that can be None

**To Reproduce**
parse a json from a demo to a pandas dataframe and inspect the kills dataframe. the playerTradedSteamID is likely to have this error as many of the rows have None in this column

**Expected behavior**
any column contain a SteamID should be an integer

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by pnxenopoulos** [comment]
Fixed for all dfs, going to put in a PR soon once I fix #149

**Comment by pnxenopoulos** [comment]
Fixed in #150
