### ISSUE TITLE
Wrong / strange rounds catched in gameRounds

### ISSUE THREAD

**Issue by kenmareirl** [pnxenopoulos/awpy#149]
**Describe the bug**
Score switched between rounds and one (or more) rounds created after the end of the map

**To Reproduce**
1. Go to [this demo](https://www.hltv.org/matches/2353743/anonymo-vs-ldlc-esea-premier-season-39-europe)
2. Parse the three maps
3. In map 1 and map 2 : rounds with a score which is switched, and at then end of the game, one (or more) rounds have been catched (score reset)
4. In map 3 : at the end of the game, a round has been catched with a score reset (tScore and ctScore 0 0)

**Expected behavior**
No additional rounds generated (beginning or end of the map) 

**Screenshots**
![Map1](https://user-images.githubusercontent.com/92644057/161562727-8115da89-9d65-401e-b346-02735bc930af.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by pnxenopoulos** [comment]
I'm going to add a new subfunction to `clean_rounds()`. For now, it will default be left to `False` as we test it. Will have something tmrw.

**Comment by pnxenopoulos** [comment]
Fixed in #150
