### ISSUE TITLE
Problem with tRoundStartMoney and ctRoundStartMoney (first round of each side)

### ISSUE THREAD

**Issue by kenmareirl** [pnxenopoulos/awpy#152]
**Describe the bug**
Incorrect amounts for tRoundStartMoney and ctRoundStartMoney but **only** for the first round of each side (other rounds are OK).
Using parse function + clean_rounds (same problem using or not the argument remove_bad_scoring=True).

**To Reproduce**
1. Parse the following demos : [AST-MIBR](https://www.hltv.org/matches/2354338/astralis-vs-mibr-iem-katowice-2022-play-in), [BIG-GOD](https://www.hltv.org/matches/2354569/big-vs-godsent-esl-pro-league-season-15), [G2-VIT](https://www.hltv.org/matches/2353988/g2-vs-vitality-blast-premier-spring-groups-2022)
2. Check the following fields for the JSON : tRoundStartMoney and ctRoundStartMoney 
3. Problems detected: 

- AST-MIBR and BIG-GOD : wrong amounts for both team at round 1 and round 16
- G2-VIT : inferno : wrong amounts for both team at round 16, mirage : wrong amount at round 16 for Team Vitality, incorrect amounts for both team at round 16

**Expected behavior**
For round 1 and 16 the tRoundStartMoney and ctRoundStartMoney should be 4000$ (800$ per player)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [N/A]
 - Version [N/A]

**Smartphone (please complete the following information):**
 - Device: [N/A]
 - OS: [N/A]
 - Browser [N/A]
 - Version [N/A]

**Additional context**
Other rounds work fine, no problem detected.

**Comment by pnxenopoulos** [comment]
Interesting...when you look at the frames, the money looks fine. I imagine it has to be the fact that I'm grabbing round start money _during_ round start. 

How important is this feature? We could remove it since it is unstable.

**Comment by pnxenopoulos** [comment]
I think I'll have better success with manually implementing these keys, which is what I'll do. Even in frames, I'll just loop through and sum

**Comment by pnxenopoulos** [comment]
Think the best approach here is to just calculate this by looking on the FreezeTimeEnd. Sometimes demos may miss that, not much we can do!

**Comment by pnxenopoulos** [comment]
Addressed in #166
