### ISSUE TITLE
Dead player flashed

### ISSUE THREAD

**Issue by kenmareirl** [pnxenopoulos/awpy#153]
**Describe the bug**
In the flashes events, several dead player are present. 

**To Reproduce**
1. Use [this demo]( https://www.hltv.org/stats/matches/mapstatsid/136098/big-vs-godsent)
2. Check round 4 with the flash throwed by tabseN and the round 9 throwed by dumau
3. Several players are flashed but already dead
4. Another example in [this demo](https://www.hltv.org/stats/matches/mapstatsid/136091/godsent-vs-big)
5. Check round 3 with the flash throwed by syrson.
6. tabseN is flashed but already dead.

**Expected behavior**
Dead players should not appear as flashed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [N/A]
 - Version [N/A]

**Smartphone (please complete the following information):**
 - Device: [N/A]
 - OS: [N/A]
 - Browser [N/A]
 - Version [N/A]

**Additional context**
N/A

**Comment by pnxenopoulos** [comment]
Easy fix

**Comment by pnxenopoulos** [comment]
I think it is good in #157 (you can pip install), let me know

**Comment by kenmareirl** [comment]
Works perfectly !
