### ISSUE TITLE
Enemy Flashed 0 / Teammates flashed really high

### ISSUE THREAD

**Issue by ma1n** [pnxenopoulos/awpy#155]
![image](https://user-images.githubusercontent.com/13312354/165325511-aface592-9d6b-4485-ae77-a6990bf3c722.png)

![image](https://user-images.githubusercontent.com/13312354/165325537-a7b6c1fd-a98d-4439-bd63-55a0ced7565c.png)

![image](https://user-images.githubusercontent.com/13312354/165325554-3dea19a3-4f89-488f-bf2c-e9f340e716a2.png)

**Comment by pnxenopoulos** [comment]
Check out the new player_stats function in the 1-update branch

Just tested and enemies flashed works now. The problem has to do with both teams being empty strings
