### ISSUE TITLE
NoneType object is not iterable with ESEA Demo

### ISSUE THREAD

**Issue by ma1n** [pnxenopoulos/awpy#156]
ESEA Demo results in Stats Module broken
  
Demo in question: https://we.tl/t-mZ2r9WTgLk  

![image](https://user-images.githubusercontent.com/13312354/165355137-2d5c92a8-1d4c-452e-8c37-b3035fa3659e.png)

**Comment by pnxenopoulos** [comment]
Do you have a link to the ESEA match? It seems like in the first round, `ctSide` and `tSide` have no players listed.

**Comment by pnxenopoulos** [comment]
Ah, I know what it is.

I haven't moved the following feature to be default yet. This creates a clean demo (I assume the demo is this https://play.esea.net/match/16897599).

```
p = DemoParser(...)
d = p.parse()
d = p.clean_rounds(remove_bad_scoring=True)
```
