### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by nicodemuz-zz** [pnxenopoulos/awpy#158]
**Describe the bug**
If a player haven't died or haven't killed anyone there is a couple of cases with division by 0 for me in stats.py at lines 204 and 221. I fixed it for myself by adding an if at the end of the rows like this:

- 204: player_statistics[player]["kills"] / player_statistics[player]["deaths"] if player_statistics[player]["deaths"] != 0 else player_statistics[player]["kills"],
- 221: player_statistics[player]["hs"] / player_statistics[player]["kills"] if player_statistics[player]["kills"] != 0 else 0, 2

**To Reproduce**
1. Record a session where the gamer doesn't die or doesn't kill (often only happens with very few rounds recorded)
2. Analyze the recorded .dem
demo_parser = DemoParser(...)
data = demo_parser.parse()
3. See error

**Expected behavior**
Not a division by 0 error, either nothing is calculated or a proper value is chosen based on what is looked for like in the example solution

**Comment by pnxenopoulos** [comment]
Hi @nicodemuz-zz, thanks for spotting and reporting this error! 

How crucial is this error to your workflow? If it isn't crucial, I'll just wrap it up in the next release. If it's important, I can make a separate release just for this.

**Comment by nicodemuz-zz** [comment]
Not crucial at all, so wrap it up for a future release. :)

**Comment by pnxenopoulos** [comment]
Keeping open so I don't forget!

**Comment by pnxenopoulos** [comment]
Fixed in #160
