### ISSUE TITLE
Tick in announcementFinalRound missing for some overtime

### ISSUE THREAD

**Issue by kenmareirl** [pnxenopoulos/awpy#159]
**Describe the bug**
matchPhases > announcementLastRoundHalf contains tick for the last round before half time and tick for the last round before half time in overtime
However in matchPhases > announcementFinalRound contains only tick for the last round (num 30) but not the last round of the overtime

**To Reproduce**
1. Parse [this demo](https://www.hltv.org/matches/2354404/g2-vs-faze-iem-katowice-2022)
2. See the problem for map 1 (1 overtime) and map 2 (6 overtimes)

In [this demo](https://www.hltv.org/matches/2353975/natus-vincere-vs-astralis-blast-premier-spring-groups-2022) it is OK (having both tick rate event for announcementFinalRound)

**Expected behavior**
Always have a tickrate for announcementLastRoundHalf in overtime.

**Screenshots**
N/A

**Comment by pnxenopoulos** [comment]
According to Markus' documentation, "AnnouncementFinalRound signals the 30th round, not raised if the match ends before that."

Thus, this looks like the intended behavior. Feel free to respond or reopen if you have any questions. Perhaps I can fix the awpy documentation to clear this up.
