### ISSUE TITLE
Access specific frame data

### ISSUE THREAD

**Issue by krystalgamer** [pnxenopoulos/awpy#167]
**Is your feature request related to a problem? Please describe.**
I'd like to know how a player's view is moving before and after killing someone. The thing is that the frames dataframe only has some frames.

**Describe the solution you'd like**

I know getting all frames in a DataFrame format would be insane. I was thinking of the possibility of sending an interval of ticks and it converts them to a DataFrame.

**Comment by pnxenopoulos** [comment]
This is a common request, and one that I think would be valuable. However, it is likely something that will happen down the road.

**Comment by pnxenopoulos** [comment]
Hey @krystalgamer, I will be working on #192 so that we can parse frames and player-frames into CSVs, rather than JSON. Keep at eye on that one, as I will work on it in the next few days

**Comment by pnxenopoulos** [comment]
Update: check out https://github.com/pnxenopoulos/csgo-tick-parser

Does this help in any way?

**Comment by pnxenopoulos** [comment]
Closing for now. Let me know if the above didn't work.

**Comment by krystalgamer** [comment]
oh sorry for not responding. I haven't picked up the project since july. if i comeback to it I'll definitely update the thread!
