### ISSUE TITLE
Bug with Kast

### ISSUE THREAD

**Issue by Iris0o** [pnxenopoulos/awpy#174]
**Describe the bug**

The player was eliminated at the beginning of the round, and I think because of this he cannot be added to KAST

I looked in KAST for this round and there is no SteamID
`{76561199209024832: {'k': False, 'a': False, 's': True, 't': False}, 76561198282998544: {'k': False, 'a': False, 's': True, 't': False}, 76561198836354295: {'k': False, 'a': False, 's': True, 't': False}, 76561198983114746: {'k': False, 'a': False, 's': True, 't': False}, 76561198404101540: {'k': False, 'a': False, 's': True, 't': False}, 76561198346844741: {'k': False, 'a': False, 's': True, 't': False}, 76561199121310338: {'k': False, 'a': False, 's': True, 't': False}, 76561198147411997: {'k': False, 'a': False, 's': True, 't': False}, 76561198283382514: {'k': False, 'a': False, 's': True, 't': False}}`

preveosly round: 
`{76561198404101540: {'k': True, 'a': False, 's': True, 't': False}, 76561199209024832: {'k': True, 'a': False, 's': True, 't': False}, 76561198282998544: {'k': False, 'a': False, 's': False, 't': True}, 76561198983114746: {'k': True, 'a': False, 's': False, 't': False}, 76561198836354295: {'k': False, 'a': False, 's': False, 't': False}, 76561199099834811: {'k': False, 'a': False, 's': False, 't': False}, 76561198283382514: {'k': True, 'a': False, 's': False, 't': False}, 76561198147411997: {'k': True, 'a': False, 's': True, 't': False}, 76561199121310338: {'k': False, 'a': False, 's': False, 't': False}, 76561198346844741: {'k': True, 'a': False, 's': False, 't': False}}`

`Traceback (most recent call last):
  File "main.py", line 47, in <module>
    player_stats_json = player_stats(data["gameRounds"])
  File "%AppData%\Local\Programs\Python\Python310\lib\site-packages\awpy\analytics\stats.py", line 130, in player_stats
    kast[k["victimSteamID"]]["s"] = False
KeyError: 76561199099834811`

**Match**: `steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-5Z8Ww-85oO8-YWqRC-UWGii-xOYQM`
**Time**: `'tick': 71050, 'seconds': 1110.15625, 'roundnum': 11`
**Player**: `'SteamID': 76561199099834811, 'attackerName': 'Firsøv'

[match730_003555112031260508424_1358874782_145.json.txt](https://github.com/pnxenopoulos/awpy/files/8933338/match730_003555112031260508424_1358874782_145.json.txt)
`

**Comment by pnxenopoulos** [comment]
Does the most recent update help? It's 1.1.8, see Discord for instructions on how to upgrade.

And if not, would you happen to have the `.dem` for this that I could check? I think the 30-day retention for the match has passed.

**Comment by Iris0o** [comment]
I'm sorry, but I didn't find a match

**Comment by Iris0o** [comment]
> Does the most recent update help? It's 1.1.8, see Discord for instructions on how to upgrade.
> 
> And if not, would you happen to have the `.dem` for this that I could check? I think the 30-day retention for the match has passed.

the bug is still there

**Comment by Iris0o** [comment]
mb use this `if (victim_key == killer_key) and (victim_key not in kast.keys()): `

**Comment by Iris0o** [comment]
`if (victim_key == killer_key) and (victim_key not in kast.keys()):
                    kast[str(k["steamID"]) + " - " + k["playerName"]] = {}
                    kast[str(k["steamID"]) + " - " + k["playerName"]]["k"] = False
                    kast[str(k["steamID"]) + " - " + k["playerName"]]["a"] = False
                    kast[str(k["steamID"]) + " - " + k["playerName"]]["s"] = False
                    kast[str(k["steamID"]) + " - " + k["playerName"]]["t"] = False`

**Comment by Iris0o** [comment]
![image](https://user-images.githubusercontent.com/57287423/186769161-2f917249-8b29-4bdf-bc90-c0ee90311229.png)

**Comment by Iris0o** [comment]
![image](https://user-images.githubusercontent.com/57287423/186769510-2becb820-e95f-4cf5-b7c1-3ed0ebdfcbd6.png)

**Comment by RunGuitarMan** [comment]
@pnxenopoulos Hello! I think I've run into the same bug.
![image](https://user-images.githubusercontent.com/4107440/194768491-97ced9f2-ef8a-4066-a26c-70686410cfd4.png)

gaenerated JSON have size ~30 Mb
[1-1e95abf4-31c8-46f9-bdd2-a38af8a240e1-3-1.json.zip](https://github.com/pnxenopoulos/awpy/files/9742032/1-1e95abf4-31c8-46f9-bdd2-a38af8a240e1-3-1.json.zip)

FACEIT match link: https://www.faceit.com/ru/csgo/room/1-1e95abf4-31c8-46f9-bdd2-a38af8a240e1

Demofile here: https://demos-europe-west2.faceit-cdn.net/csgo/1-1e95abf4-31c8-46f9-bdd2-a38af8a240e1-3-1.dem.gz
google.drive mirror(if deleted): https://drive.google.com/file/d/1__EmuxcMcLY04F8SIugtVh5z87weDcpz

1-1e95abf4-31c8-46f9-bdd2-a38af8a240e1-3-1.dem file ~238Mb unarchived

**Comment by RunGuitarMan** [comment]
@pnxenopoulos I carefully looked at the record. At the score of 21-21, the second team pauses and during the pause the "problem" player reconnect to the game.
He manages to connect before the start of the round and plays normally. There are no more anomalies.

@Iris0o Tell me, were you able to solve this problem? If yes, what is it? And how exactly can it be fixed?

**Comment by RunGuitarMan** [comment]
I checked a few more similar demos and here are the results. It seems that if player reconnect in a "kill-round" or exit before the end of the last round, we will get this error.

Example demos: https://drive.google.com/file/d/1h5q0PJ0hs0A-_eGfHM1_JEm1MtiLvQuE
'1-1e95abf4-31c8-46f9-bdd2-a38af8a240e1-3-1.dem', KeyError(76561199010208041) - **reconnect on 21-21 (on freeze time) and he makes kill in the round**
'1-2129cfb8-0c72-4f90-9bcc-64a46b54aed8-3-1.dem', KeyError(76561198077756521) - **reconnect on 0-0 (freeze time) and makes kill in first round**
'1-46e7e99e-e10c-48cd-a5ee-b34c013f2868-2-1.dem', KeyError(76561198171591411) - **disconnected before last round ends (no kills on that round and round before)**
'1-dccff229-6504-443c-a804-3cd704e2653f-3-1.dem', KeyError(76561198089453150) - **disconnected before last round ends and makes kills in last round and round before**

**Comment by RunGuitarMan** [comment]
Сancel that, guys. My mistake. 
I was completely sure that I had the latest version of awpy, but it turned out not to be >_<
God... 3+ hours of watching and analyzing the csgo demo... Seems like it's not worth working late at night. >_<

**Comment by pnxenopoulos** [comment]
@RunGuitarMan @Iris0o what about with the most recent version?

**Comment by JanEricNitschke** [comment]
I just tested the current release (1.3.1) with the parsed json files [here](https://drive.google.com/file/d/1h5q0PJ0hs0A-_eGfHM1_JEm1MtiLvQuE) and [here]([match730_003555112031260508424_1358874782_145.json.txt](https://github.com/pnxenopoulos/awpy/files/8933338/match730_003555112031260508424_1358874782_145.json.txt) and did not get any errors.

So i will assume this is fixed and close the issue.

Feel free to reopen (or make a new one) if you still have demos that crash during `player_stats`
