### ISSUE TITLE
Incorrect tickrate calculation

### ISSUE THREAD

**Issue by pavelloca** [pnxenopoulos/awpy#178]
**Description**
The problem is that there is an incorrect rounding of the tick rate. After parsing, I saw that my frame length differs per second, 127 and 128. But there can only be two values for the tick rate in the game: 64 and 128. It seems to me that the problem is in data type conversion (as I showed in the last screenshot).

**Screenshots**

- This screenshot shows one of the examples in the library repository, specifically [this one](https://github.com/pnxenopoulos/awpy/blob/a61ba41cd91f01828ec2a309322a1107f84b9121/examples/00_Parsing_a_CSGO_Demofile.ipynb). As I said earlier, tick rate 127 cannot exist.

![1](https://user-images.githubusercontent.com/63933338/180729360-e225a292-aac2-4121-9d3b-4695cfd5e415.png)

- This screenshot shows the part of the code that I think is causing this problem. The piece of code is taken from [this file](https://github.com/pnxenopoulos/awpy/blob/8285602fed83feb2bde5ceb14c3dae235cf74e96/awpy/parser/parse_demo.go#L949).

![2](https://user-images.githubusercontent.com/63933338/180729377-b1abbfdc-961c-4c51-a698-eb8d71a1a56d.png)

- This screenshot shows the rounding logic that has been broken.

![4](https://user-images.githubusercontent.com/63933338/180729388-853359a5-6d9c-4b4b-877e-7d329fea086b.png)

**Comment by JanEricNitschke** [comment]
@pavelloca thanks for creating the issue.

I think the fix for this would be to use  `int64(math.Round(p.TickRate()))` instead of just `int64(p.TickRate())`

**Comment by pavelloca** [comment]
Yes, indeed, a small change of part of the code solves the problem with this bug, most likely

**Comment by pnxenopoulos** [comment]
Thanks for solving this. Check out the 1.1.8 release #179 and the Discord
