### ISSUE TITLE
Same nicknames

### ISSUE THREAD

**Issue by Iris0o** [pnxenopoulos/awpy#183]
**Describe the bug**
If the player changed his nickname in the game, then there will be more elements in player_stats

**Screenshots**
![image](https://user-images.githubusercontent.com/57287423/183906974-5126553b-6d86-4db5-bdc4-23a578ed1eac.png)

[match730_003564561176207556835_0769000825_349 .json.txt](https://github.com/pnxenopoulos/awpy/files/9300195/match730_003564561176207556835_0769000825_349.json.txt)

**Comment by Iris0o** [comment]
I changed my nickname(IRIS0) to my friend's nickname(leshasharf) when he flew out

**Comment by JanEricNitschke** [comment]
Would be solved by changing https://github.com/pnxenopoulos/awpy/blob/main/awpy/analytics/stats.py#L17

`player_statistics[str(p["steamID"]) + " - " + p["playerName"]]` in https://github.com/pnxenopoulos/awpy/blob/main/awpy/analytics/stats.py#L17 (and everywhere else there)
to:
`player_statistics[p["playerName"] if p["steamID"] == 0 else str(p["steamID"])]`
