### ISSUE TITLE
isBot

### ISSUE THREAD

**Issue by Iris0o** [pnxenopoulos/awpy#184]
in stats.py missing line isBot in t_side

**Comment by JanEricNitschke** [comment]
Being adressed: https://github.com/pnxenopoulos/awpy/commit/fe510fb6ebba8080b4fa352800b330ee5a9ea09a

**Comment by JanEricNitschke** [comment]
Has been adressed: https://github.com/pnxenopoulos/awpy/commit/142583e72d2de9990a3271663e6bfe0d69784164#diff-298f0bf26aaad42c9c163f69bba432beedac14f685c6c593957e46ae344ab480R85
