### ISSUE TITLE
assist = 0

### ISSUE THREAD

**Issue by Iris0o** [pnxenopoulos/awpy#185]
`if (
                k["assisterSteamID"]
                and k["assisterTeam"] != k["victimTeam"]
                and assister_key in player_statistics.keys()
            ):
                player_statistics[assister_key]["assists"] += 1
                kast[assister_key]["a"] = True`

in MM k["assisterTeam"] and  k["victimTeam"] == ""

**Comment by JanEricNitschke** [comment]
Being adressed: https://github.com/pnxenopoulos/awpy/commit/fe510fb6ebba8080b4fa352800b330ee5a9ea09a

**Comment by JanEricNitschke** [comment]
This should have been solved by now so im closing it. In case this somehow still remains feel free to reopen with an example demo.
