### ISSUE TITLE
Add handling for NoneType objects in generate_vector_state()

### ISSUE THREAD

**Issue by mat-gys** [pnxenopoulos/awpy#187]
**Is your feature request related to a problem? Please describe.**
When utilizing the function `generate_vector_state`, there's an Error if the `frame["t"]["players"]`  (or `frame["ct"]["players"]`) is `None`.

**Describe the solution you'd like**
For the function to not update the values and maybe give a warning, so that the code run but you are aware that there's a round for which you have no information on certain players.

**Additional context**
The error that's given is `Nonetype object is not iterable`

**Comment by pnxenopoulos** [comment]
Hey @mat-gys, this makes sense. We'll work it into the next update!

**Comment by JanEricNitschke** [comment]
I think this has also been fixed with https://github.com/pnxenopoulos/awpy/commit/142583e72d2de9990a3271663e6bfe0d69784164
