### ISSUE TITLE
NAV_CSV data for Anubis and Tuscan?

### ISSUE THREAD

**Issue by kostrykin** [pnxenopoulos/awpy#188]
**Is your feature request related to a problem? Please describe.**
When working with `awpy.data.NAV_CSV`, there is data for de_dust2, de_inferno, de_vertigo, and others, but de_anubis and de_tuscan are missing.

**Describe the solution you'd like**
It would be great if `awpy.data.NAV_CSV` was extended by data for de_anubis and de_tuscan.

**Comment by pnxenopoulos** [comment]
Thanks for finding this. We'll get that in with the next update.

**Comment by pnxenopoulos** [comment]
Added in #209
