### ISSUE TITLE
Error while parsing a demo in two parts

### ISSUE THREAD

**Issue by kenmareirl** [pnxenopoulos/awpy#189]
**Describe the bug**
When a demo is splitted in two parts, an error is raised while parsing the first one.

**Include Information to Reproduce**

- Download [this demo](https://www.hltv.org/matches/2357663/liquid-vs-ninjas-in-pyjamas-blast-premier-fall-groups-2022)
- Try to parse overpass p1
- The error is raised (see screenshots)

**Screenshots**
![parse_part_1](https://user-images.githubusercontent.com/92644057/188329413-1e408308-e338-47bc-921f-502d18a95a27.png)

**Additional context**
Even with this error a json is generated.

**Comment by pnxenopoulos** [comment]
Thanks for finding this @kenmareirl. This may require some sort of additional function.

**Comment by kenmareirl** [comment]
you're welcome 👍

**Comment by JanEricNitschke** [comment]
I don't know if this is something we need to to address at all. This error is raised directly from the go parser and we panic on it at the very end.

I guess it would probably make more sense to print a warning here that the demo ended unexpectedly and to double check the resulting json file.
