### ISSUE TITLE
Add velocity information to 'damages' and 'weaponFires' fields

### ISSUE THREAD

**Issue by jlirms** [pnxenopoulos/awpy#191]
**Is your feature request related to a problem? Please describe.**
Without velocity information in 'damages' or 'weaponFires' we cannot know if a player is shooting while retreating, committing to a peak or got lucky in run-and-gun situations
Currently we have to go back to the most recent frame to get the velocity of the players engaged in the fight

**Describe the solution you'd like**
Add a velocity, velocityY, velocityZ to the damages, weaponFires fields just as we have for the frames field

**Additional context**
We don’t need this for the `kills` field because we can use parse_kill_frames = True :)

**Comment by pnxenopoulos** [comment]
Thanks for the issue. Likely this was intended for CSGO, but we now have this in the CS2 parser.

It's currently in the `2.0.0b5` branch, which you can install with `pip install git+https://github.com/pnxenopoulos/awpy@v2.0.0b5`

we include the `velocity_X/Y/Z` fields by default for weapon fire events.
