### ISSUE TITLE
Access to game chat data

### ISSUE THREAD

**Issue by artkulak** [pnxenopoulos/awpy#194]
**Is your feature request related to a problem? Please describe.**
CSGO demos contain chat data if you inspect them specifically through CSGO built-in demo viewer. But I can't find this information anywhere in the parsed dem file. Is it possible to add this at all?
I also wonder if there is a possibility to access audio chat because, from what I have seen, this information is stored in the DEM file as well.

**Describe the solution you'd like**
It would be nice to have access to chat messages in the frames for each game round

**Comment by Fmestre96** [comment]
I second this!

**Comment by pnxenopoulos** [comment]
How about we do something like this -- we can make it a parsing parameter. Maybe like `chat=True`, then, there can be a a top level key called chat that produces something like this:

```
...,
"chat": [
   {
      "playerName": "xeno",
      "message": "i love awpy",
      "tick": 1234
   }, ...
]
```

any other data to round out this object?

**Comment by Fmestre96** [comment]
I've made some changes in my fork to support chat messages (ChatMessage, SayText, SayText2)
Here's the pull request 

https://github.com/pnxenopoulos/awpy/pull/214
