### ISSUE TITLE
kill doesn't get detected in pro game

### ISSUE THREAD

**Issue by ozanhagen** [pnxenopoulos/awpy#219]
https://www.hltv.org/matches/2348399/budapest-five-vs-gorillaz-blast-rising-2021

a kill happens in the first map (nuke) , sunny kills fleav in round 18/30,
however it does not seem to get picked up.
the HLTV stats include the kill though (as kill for sunny and death for fleav).

The kill does not appear in the killfeed when watching the demo in game.

**Comment by ozanhagen** [comment]
same issue:
https://www.hltv.org/matches/2355813/players-vs-astralis-pgl-major-antwerp-2022-europe-rmr-b
dust2, round 25, ax1le killing blamef not getting detected

**Comment by ozanhagen** [comment]
third example of the issue happening:
https://www.hltv.org/matches/2360642/liquid-vs-natus-vincere-blast-premier-world-final-2022
elige killing s1mple in round 18

**Comment by pnxenopoulos** [comment]
Yes, I have come across this issue before. I'm not sure the best way to handle this -- if the kill isn't logged, we can't really infer _who_ did the kill. 

This is a recurring issue though. Perhaps it is worth some investigation.

**Comment by JanEricNitschke** [comment]
I do not think there is anything we can reasonably do for this. If the demo straight up does not contain the event then there is nothing we can do.

I would close this for now. Feel free to reopen if this becomes more common or there is new information about how to potentially circumvent it.
