### ISSUE TITLE
esea pro demo halftime round clearing issue

### ISSUE THREAD

**Issue by ozanhagen** [pnxenopoulos/awpy#220]
https://www.hltv.org/matches/2353775/party-astronauts-vs-extra-salt-esea-premier-season-39-north-america
map: inferno

after the first half, on esea there is usually some additional warmup until the players ready up
seems like the kills in that warmup did not get cleared? 

seems like there are 31 rounds logged, while there were only 28 played.

for example player "floppy" killing player "Infinite" in tick 262075. 
the total kill sum has 7 more kills than what the hltv stats show.

**Comment by pnxenopoulos** [comment]
did you try parsing with cleaning (`.parse(clean=True)`) and see if the warmups don't get cleaned? Probably will have to revisit the cleaning method.
