### ISSUE TITLE
Counter-Strike 2 demo parsing

### ISSUE THREAD

**Issue by TomQWERTY** [pnxenopoulos/awpy#222]
Hello, do you have plans to add CS2 demo files support?

**Comment by JanEricNitschke** [comment]
Yes, we are planning to. As awpy relies on demoinfocs-golang for the bare parsing of the demo we will try to include it once that has been updated. 

The work for that is currently being tracked here: https://github.com/markus-wa/demoinfocs-golang/pull/383

**Comment by TomQWERTY** [comment]
> Yes, we are planning to. As awpy relies on demoinfocs-golang for the bare parsing of the demo we will try to include it once that has been updated.
> 
> The work for that is currently being tracked here: [markus-wa/demoinfocs-golang#383](https://github.com/markus-wa/demoinfocs-golang/pull/383)

thanks for your answer, happy to hear that!

**Comment by JanEricNitschke** [comment]
First alpha version of demoinfocs-golang with cs2 support: https://github.com/markus-wa/demoinfocs-golang/releases/tag/v3.4.0-alpha.0

**Comment by hojlund123** [comment]
As promised @JanEricNitschke 
Relevant for adding skins to CS2 
https://github.com/LaihoE/demoparser/blob/main/src/python/src/lib.rs

**Comment by jotalanusse** [comment]
Any updates on CS2 support now that replays are back?

**Comment by JanEricNitschke** [comment]
@jotalanusse There is work being done here: https://github.com/pnxenopoulos/awpy/pull/301

and there should be some support in this branch: https://github.com/pnxenopoulos/awpy/tree/awpy2-markus

Best to join the discord server and checkout the "updates" tab.

**Comment by jotalanusse** [comment]
Thanks @JanEricNitschke, and by any chance do you know how to fix the missing `distutils` module error during the installation of awpy2 with Python 3.12?

**Comment by JanEricNitschke** [comment]
@jotalanusse Thats an issue with the dependencies. The version of numpy we are using in the main branch does not support Python 3.12. I have a PR that updates the dependencies that fixes that.

**Comment by pnxenopoulos** [comment]
> Thanks @JanEricNitschke, and by any chance do you know how to fix the missing `distutils` module error during the installation of awpy2 with Python 3.12?

I think also the `demoparser2` dependency only works on 3.11 and below for now

**Comment by pnxenopoulos** [comment]
The Awpy 2 beta supports CS2 parsing: https://github.com/pnxenopoulos/awpy (it has for a while, but I forgot this issue was open!)

Please open new issues as you see fit!
