### ISSUE TITLE
Incorporate new types from Map Control PR into rest of awpy package

### ISSUE THREAD

**Issue by adisujithkumar** [pnxenopoulos/awpy#240]
The [map control PR](https://github.com/pnxenopoulos/awpy/pull/235) introduces a few new types to awpy. However, they are not integrated into the rest of the package (nav, demoparser, etc.). This issue is meant to track the work to merge these new types into the rest of the package in the future. 

Running list of types to integrate:
TileId - Could be incorporated into nav, maybe demoparser
TileDistanceObject - Could be combine with TileDistance so there is one overall type that handles all functionalities needed
TileNeighbors - Could be merged into nav as part of a  Nav Tile object/TypeHint re-work overall, but might be optional

**Comment by JanEricNitschke** [comment]
I am not sure how to best combine the TileDistanceObject with the "normal" DistanceObject. 

`DistanceObject` holds the distance and path between two tiles. 

`TileDistanceObject` holds the distance to an unspecified source tile as well as the tileid of the current tile if i understood it correctly.

My first idea would be to remove `TileDistanceObject` and instead use distanceobject, specify some distance type (is it euclidean?) and just have the path either be length 1 with just the current tile or length 2 with the source tile and the current tile.

**Comment by JanEricNitschke** [comment]
On second thought that actually sounds perfect. We could literally just change `area_distance` to have source and destination ids as the path and then we have it already. Then you wouldnt need to wrap the result in a TileDistanceObject to begin with.
