### ISSUE TITLE
Investigate whether CV2 dependency can be removed

### ISSUE THREAD

**Issue by adisujithkumar** [pnxenopoulos/awpy#241]
CV2 is used for resize in a few functions in plot.py. However, it might be possible to avoid using cv2. resize and instead use numpy functions on the images/np arrays itself. The [map control PR](https://github.com/pnxenopoulos/awpy/pull/235) is still in progress now so documenting here for future investigation.

**Comment by JanEricNitschke** [comment]
This can be closed, right? CV2 didnt become a dependency to begin with?

**Comment by adisujithkumar** [comment]
Yup it can be closed; it's no longer a dependency
