### ISSUE TITLE
Investigate whether AREA_DIST_MATRIX can be used to Map Control purposes

### ISSUE THREAD

**Issue by adisujithkumar** [pnxenopoulos/awpy#243]
Map Control [PR](https://github.com/pnxenopoulos/awpy/pull/235) currently doesn't utilize AREA_DIST_MATRIX for any calculations. Investigation should be done in the future to see whether it makes sense to utilize the AREA_DIST_MATRIX when available.

**Comment by pnxenopoulos** [comment]
Closing for Awpy 2.0
