### ISSUE TITLE
Move some of the types from TypedDict to Dataclass

### ISSUE THREAD

**Issue by JanEricNitschke** [pnxenopoulos/awpy#277]
I initially just converted most dictionaries to TypedDicts for proper type checking.

However some structures would probably be better suited for dataclasses as we are not dynamically accessing their contents.

Candidates would be `MapData`, `KAST`, `ClosestArea`, `DistanceObject` and  `RoundStatistics`

This would however be a pretty breaking change as some of these types (for example DistanceObject) are returned from user facing functions.

**Comment by pnxenopoulos** [comment]
Closing for Awpy 2.0

I think we can use Pydantic going forward. Can have a broader discussion in Discord
