### ISSUE TITLE
Map Control Documentation Issues

### ISSUE THREAD

**Issue by adisujithkumar** [pnxenopoulos/awpy#279]
Keep a running list of instance of incorrect documentation w.r.t map control-related code. Once I think I have found all the instances, I will send a PR addressing them all: 

* `plot_frame_map_control` -> Documentation says it returns nothing; this is incorrect
* `_approximate_neighbors` -> Documentation says "n" instead of "n_neighbors"
* `_calc_map_control_metric_from_dict`, `calc_frame_map_control_metric` -> Documentation states "Each tile is given a value between -1 (complete T control) and 1 (complete CT control)"; this is incorrect.

**Comment by pnxenopoulos** [comment]
Closing for Awpy 2.0
