### ISSUE TITLE
Have plot_map_control_metrics return figure object

### ISSUE THREAD

**Issue by adisujithkumar** [pnxenopoulos/awpy#280]
Slight change to have plot_map_control_metrics return the figure object instead of using plt.show() within the function. Returning the figure object would align the function similarly to the rest of the plot.py file (which usually returns the figure, axes tuple back to the user). If the user is able to have the figure returned back, they can do whatever they like (use tight layout, save to file, custom annotations, etc.). If others think this change would be beneficial - I'll send a PR for this issue by the end of the weekend.

**Comment by pnxenopoulos** [comment]
Closing for Awpy 2.0
