### ISSUE TITLE
thread '<unnamed>' panicked

### ISSUE THREAD

**Issue by TomQWERTY** [pnxenopoulos/awpy#302]
I was trying to test awpy 2.0 dev version with some of my premier and matchmaking demos. While trying to parse one of them, I've got error message saying "thread '<unnamed>' panicked at D:\a\demoparser\demoparser\src\parser\src\sendtables.rs:513:20:
index out of bounds: the len is 1 but the index is 4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
I don't see any reason why this happened to this very demo.
Code was just something like
from awpy import parse_demo
parsed = parse_demo(file=r"file_name.dem")
print(parsed["header"])

Here is the demo: https://drive.google.com/file/d/1r2HrcC-EcNkG3s9hpjVAizy8TroO04D3/view?usp=drive_link

It was recorded today (10/31/2023). Also maybe worth mentioning, that I have another demo that was recorded today too, and it doesn't give such an error, it is parsed fine.

**Comment by pnxenopoulos** [comment]
I think there is limited support for parsing MM-related demos currently. Guessing this was recorded as a POV demo?

**Comment by TomQWERTY** [comment]
> I think there is limited support for parsing MM-related demos currently. Guessing this was recorded as a POV demo?

I'm not sure what does POV demo mean, but this one was recorded by typing "record *fileName*" in console at the beginning of the match

**Comment by pnxenopoulos** [comment]
> > I think there is limited support for parsing MM-related demos currently. Guessing this was recorded as a POV demo?
> 
> I'm not sure what does POV demo mean, but this one was recorded by typing "record _fileName_" in console at the beginning of the match

Yup, this is a POV demo, meaning it is recorded on the player's side, not the server's (like the ones you see on HLTV).

Unfortunately, this is a rather old demo, and support for old demos, particularly from that time period (October '23) is generally not supported as the demo functionality was rather raw. If you run into other issues, please feel free to open up other issues -- I think there should be some level of support for POV demos now.
