### ISSUE TITLE
Create sample public data set 

### ISSUE THREAD

**Issue by pnxenopoulos** [pnxenopoulos/awpy#37]
A publicly hosted data set would be useful to the greater sports analytics community. In addition to the dataset, a contribution like the paper [here](https://www.nature.com/articles/s41597-019-0247-7.pdf) would be useful.

UPDATE: Will target Scientific Data journal for this...probably will work on it more over Christmas time.
UPDATE 2: Neurips also has a data paper track. Worth considering.

**Comment by billfreeman44** [comment]
👀

**Comment by JanEricNitschke** [comment]
This can probably be closed now, right?

https://github.com/pnxenopoulos/esta

https://arxiv.org/abs/2209.09861

**Comment by billfreeman44** [comment]
👍
